// Code generated by mockery v2.51.0. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/edgexfoundry/go-mod-core-contracts/v4/dtos/common"

	errors "github.com/edgexfoundry/go-mod-core-contracts/v4/errors"

	mock "github.com/stretchr/testify/mock"

	requests "github.com/IOTechSystems/go-mod-central-ext/v4/pkg/dtos/requests"

	responses "github.com/IOTechSystems/go-mod-central-ext/v4/pkg/dtos/responses"
)

// AuthClient is an autogenerated mock type for the AuthClient type
type AuthClient struct {
	mock.Mock
}

// Auth provides a mock function with given fields: ctx, headers
func (_m *AuthClient) Auth(ctx context.Context, headers map[string]string) (common.BaseResponse, errors.EdgeX) {
	ret := _m.Called(ctx, headers)

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 common.BaseResponse
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) (common.BaseResponse, errors.EdgeX)); ok {
		return rf(ctx, headers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) common.BaseResponse); ok {
		r0 = rf(ctx, headers)
	} else {
		r0 = ret.Get(0).(common.BaseResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string) errors.EdgeX); ok {
		r1 = rf(ctx, headers)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// AuthGraphQL provides a mock function with given fields: ctx, headers, req
func (_m *AuthClient) AuthGraphQL(ctx context.Context, headers map[string]string, req requests.AuthGraphQLRequest) (common.BaseResponse, errors.EdgeX) {
	ret := _m.Called(ctx, headers, req)

	if len(ret) == 0 {
		panic("no return value specified for AuthGraphQL")
	}

	var r0 common.BaseResponse
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, requests.AuthGraphQLRequest) (common.BaseResponse, errors.EdgeX)); ok {
		return rf(ctx, headers, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, requests.AuthGraphQLRequest) common.BaseResponse); ok {
		r0 = rf(ctx, headers, req)
	} else {
		r0 = ret.Get(0).(common.BaseResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string, requests.AuthGraphQLRequest) errors.EdgeX); ok {
		r1 = rf(ctx, headers, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// AuthRoutes provides a mock function with given fields: ctx, headers, reqs
func (_m *AuthClient) AuthRoutes(ctx context.Context, headers map[string]string, reqs []requests.AuthRouteRequest) (responses.AuthRouteResponse, errors.EdgeX) {
	ret := _m.Called(ctx, headers, reqs)

	if len(ret) == 0 {
		panic("no return value specified for AuthRoutes")
	}

	var r0 responses.AuthRouteResponse
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, []requests.AuthRouteRequest) (responses.AuthRouteResponse, errors.EdgeX)); ok {
		return rf(ctx, headers, reqs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string, []requests.AuthRouteRequest) responses.AuthRouteResponse); ok {
		r0 = rf(ctx, headers, reqs)
	} else {
		r0 = ret.Get(0).(responses.AuthRouteResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string, []requests.AuthRouteRequest) errors.EdgeX); ok {
		r1 = rf(ctx, headers, reqs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// RefreshToken provides a mock function with given fields: ctx, headers
func (_m *AuthClient) RefreshToken(ctx context.Context, headers map[string]string) (responses.TokenResponse, errors.EdgeX) {
	ret := _m.Called(ctx, headers)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 responses.TokenResponse
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) (responses.TokenResponse, errors.EdgeX)); ok {
		return rf(ctx, headers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) responses.TokenResponse); ok {
		r0 = rf(ctx, headers)
	} else {
		r0 = ret.Get(0).(responses.TokenResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]string) errors.EdgeX); ok {
		r1 = rf(ctx, headers)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// VerificationKeyByIssuer provides a mock function with given fields: ctx, issuer
func (_m *AuthClient) VerificationKeyByIssuer(ctx context.Context, issuer string) (responses.KeyDataResponse, errors.EdgeX) {
	ret := _m.Called(ctx, issuer)

	if len(ret) == 0 {
		panic("no return value specified for VerificationKeyByIssuer")
	}

	var r0 responses.KeyDataResponse
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string) (responses.KeyDataResponse, errors.EdgeX)); ok {
		return rf(ctx, issuer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) responses.KeyDataResponse); ok {
		r0 = rf(ctx, issuer)
	} else {
		r0 = ret.Get(0).(responses.KeyDataResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) errors.EdgeX); ok {
		r1 = rf(ctx, issuer)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// NewAuthClient creates a new instance of AuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthClient {
	mock := &AuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
