// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	errors "github.com/edgexfoundry/go-mod-core-contracts/v4/errors"

	mock "github.com/stretchr/testify/mock"

	responses "github.com/IOTechSystems/go-mod-central-ext/v4/pkg/dtos/responses"
)

// TimeSeriesClient is an autogenerated mock type for the TimeSeriesClient type
type TimeSeriesClient struct {
	mock.Mock
}

// TimeSeriesByDeviceNameAndMultiResourceNamesAndTimeRange provides a mock function with given fields: ctx, deviceName, resourceNames, start, end
func (_m *TimeSeriesClient) TimeSeriesByDeviceNameAndMultiResourceNamesAndTimeRange(ctx context.Context, deviceName string, resourceNames []string, start int64, end int64) (responses.TimeSeriesResponse, errors.EdgeX) {
	ret := _m.Called(ctx, deviceName, resourceNames, start, end)

	if len(ret) == 0 {
		panic("no return value specified for TimeSeriesByDeviceNameAndMultiResourceNamesAndTimeRange")
	}

	var r0 responses.TimeSeriesResponse
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, int64, int64) (responses.TimeSeriesResponse, errors.EdgeX)); ok {
		return rf(ctx, deviceName, resourceNames, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, int64, int64) responses.TimeSeriesResponse); ok {
		r0 = rf(ctx, deviceName, resourceNames, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(responses.TimeSeriesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, int64, int64) errors.EdgeX); ok {
		r1 = rf(ctx, deviceName, resourceNames, start, end)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// TimeSeriesByDeviceNameAndResourceNameAndTimeRange provides a mock function with given fields: ctx, deviceName, resourceName, start, end
func (_m *TimeSeriesClient) TimeSeriesByDeviceNameAndResourceNameAndTimeRange(ctx context.Context, deviceName string, resourceName string, start int64, end int64) (responses.TimeSeriesResponse, errors.EdgeX) {
	ret := _m.Called(ctx, deviceName, resourceName, start, end)

	if len(ret) == 0 {
		panic("no return value specified for TimeSeriesByDeviceNameAndResourceNameAndTimeRange")
	}

	var r0 responses.TimeSeriesResponse
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64) (responses.TimeSeriesResponse, errors.EdgeX)); ok {
		return rf(ctx, deviceName, resourceName, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, int64) responses.TimeSeriesResponse); ok {
		r0 = rf(ctx, deviceName, resourceName, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(responses.TimeSeriesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, int64) errors.EdgeX); ok {
		r1 = rf(ctx, deviceName, resourceName, start, end)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// NewTimeSeriesClient creates a new instance of TimeSeriesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTimeSeriesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TimeSeriesClient {
	mock := &TimeSeriesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
