// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/IOTechSystems/go-mod-central-ext/v4/pkg/dtos/requests"
	"github.com/IOTechSystems/go-mod-central-ext/v4/pkg/dtos/responses"
	"github.com/edgexfoundry/go-mod-core-contracts/v4/dtos/common"
	"github.com/edgexfoundry/go-mod-core-contracts/v4/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewUserClient creates a new instance of UserClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserClient {
	mock := &UserClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserClient is an autogenerated mock type for the UserClient type
type UserClient struct {
	mock.Mock
}

type UserClient_Expecter struct {
	mock *mock.Mock
}

func (_m *UserClient) EXPECT() *UserClient_Expecter {
	return &UserClient_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type UserClient
func (_mock *UserClient) Add(ctx context.Context, reqs []requests.AddUserRequest) ([]common.BaseWithIdResponse, errors.EdgeX) {
	ret := _mock.Called(ctx, reqs)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 []common.BaseWithIdResponse
	var r1 errors.EdgeX
	if returnFunc, ok := ret.Get(0).(func(context.Context, []requests.AddUserRequest) ([]common.BaseWithIdResponse, errors.EdgeX)); ok {
		return returnFunc(ctx, reqs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []requests.AddUserRequest) []common.BaseWithIdResponse); ok {
		r0 = returnFunc(ctx, reqs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.BaseWithIdResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []requests.AddUserRequest) errors.EdgeX); ok {
		r1 = returnFunc(ctx, reqs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}
	return r0, r1
}

// UserClient_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type UserClient_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - reqs []requests.AddUserRequest
func (_e *UserClient_Expecter) Add(ctx interface{}, reqs interface{}) *UserClient_Add_Call {
	return &UserClient_Add_Call{Call: _e.mock.On("Add", ctx, reqs)}
}

func (_c *UserClient_Add_Call) Run(run func(ctx context.Context, reqs []requests.AddUserRequest)) *UserClient_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []requests.AddUserRequest
		if args[1] != nil {
			arg1 = args[1].([]requests.AddUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserClient_Add_Call) Return(baseWithIdResponses []common.BaseWithIdResponse, edgeX errors.EdgeX) *UserClient_Add_Call {
	_c.Call.Return(baseWithIdResponses, edgeX)
	return _c
}

func (_c *UserClient_Add_Call) RunAndReturn(run func(ctx context.Context, reqs []requests.AddUserRequest) ([]common.BaseWithIdResponse, errors.EdgeX)) *UserClient_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AllUsers provides a mock function for the type UserClient
func (_mock *UserClient) AllUsers(ctx context.Context, offset int, limit int) (responses.MultiUsersResponse, errors.EdgeX) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for AllUsers")
	}

	var r0 responses.MultiUsersResponse
	var r1 errors.EdgeX
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (responses.MultiUsersResponse, errors.EdgeX)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) responses.MultiUsersResponse); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		r0 = ret.Get(0).(responses.MultiUsersResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) errors.EdgeX); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}
	return r0, r1
}

// UserClient_AllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllUsers'
type UserClient_AllUsers_Call struct {
	*mock.Call
}

// AllUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *UserClient_Expecter) AllUsers(ctx interface{}, offset interface{}, limit interface{}) *UserClient_AllUsers_Call {
	return &UserClient_AllUsers_Call{Call: _e.mock.On("AllUsers", ctx, offset, limit)}
}

func (_c *UserClient_AllUsers_Call) Run(run func(ctx context.Context, offset int, limit int)) *UserClient_AllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserClient_AllUsers_Call) Return(multiUsersResponse responses.MultiUsersResponse, edgeX errors.EdgeX) *UserClient_AllUsers_Call {
	_c.Call.Return(multiUsersResponse, edgeX)
	return _c
}

func (_c *UserClient_AllUsers_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int) (responses.MultiUsersResponse, errors.EdgeX)) *UserClient_AllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserByName provides a mock function for the type UserClient
func (_mock *UserClient) DeleteUserByName(ctx context.Context, name string) (common.BaseResponse, errors.EdgeX) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserByName")
	}

	var r0 common.BaseResponse
	var r1 errors.EdgeX
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (common.BaseResponse, errors.EdgeX)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) common.BaseResponse); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(common.BaseResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) errors.EdgeX); ok {
		r1 = returnFunc(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}
	return r0, r1
}

// UserClient_DeleteUserByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserByName'
type UserClient_DeleteUserByName_Call struct {
	*mock.Call
}

// DeleteUserByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *UserClient_Expecter) DeleteUserByName(ctx interface{}, name interface{}) *UserClient_DeleteUserByName_Call {
	return &UserClient_DeleteUserByName_Call{Call: _e.mock.On("DeleteUserByName", ctx, name)}
}

func (_c *UserClient_DeleteUserByName_Call) Run(run func(ctx context.Context, name string)) *UserClient_DeleteUserByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserClient_DeleteUserByName_Call) Return(baseResponse common.BaseResponse, edgeX errors.EdgeX) *UserClient_DeleteUserByName_Call {
	_c.Call.Return(baseResponse, edgeX)
	return _c
}

func (_c *UserClient_DeleteUserByName_Call) RunAndReturn(run func(ctx context.Context, name string) (common.BaseResponse, errors.EdgeX)) *UserClient_DeleteUserByName_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type UserClient
func (_mock *UserClient) Login(ctx context.Context, req requests.LoginRequest) (responses.TokenResponse, errors.EdgeX) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 responses.TokenResponse
	var r1 errors.EdgeX
	if returnFunc, ok := ret.Get(0).(func(context.Context, requests.LoginRequest) (responses.TokenResponse, errors.EdgeX)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, requests.LoginRequest) responses.TokenResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(responses.TokenResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, requests.LoginRequest) errors.EdgeX); ok {
		r1 = returnFunc(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}
	return r0, r1
}

// UserClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type UserClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req requests.LoginRequest
func (_e *UserClient_Expecter) Login(ctx interface{}, req interface{}) *UserClient_Login_Call {
	return &UserClient_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *UserClient_Login_Call) Run(run func(ctx context.Context, req requests.LoginRequest)) *UserClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 requests.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(requests.LoginRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserClient_Login_Call) Return(tokenResponse responses.TokenResponse, edgeX errors.EdgeX) *UserClient_Login_Call {
	_c.Call.Return(tokenResponse, edgeX)
	return _c
}

func (_c *UserClient_Login_Call) RunAndReturn(run func(ctx context.Context, req requests.LoginRequest) (responses.TokenResponse, errors.EdgeX)) *UserClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// LoginWithHeader provides a mock function for the type UserClient
func (_mock *UserClient) LoginWithHeader(ctx context.Context, req requests.LoginRequest, headers map[string]string) (responses.TokenResponse, errors.EdgeX) {
	ret := _mock.Called(ctx, req, headers)

	if len(ret) == 0 {
		panic("no return value specified for LoginWithHeader")
	}

	var r0 responses.TokenResponse
	var r1 errors.EdgeX
	if returnFunc, ok := ret.Get(0).(func(context.Context, requests.LoginRequest, map[string]string) (responses.TokenResponse, errors.EdgeX)); ok {
		return returnFunc(ctx, req, headers)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, requests.LoginRequest, map[string]string) responses.TokenResponse); ok {
		r0 = returnFunc(ctx, req, headers)
	} else {
		r0 = ret.Get(0).(responses.TokenResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, requests.LoginRequest, map[string]string) errors.EdgeX); ok {
		r1 = returnFunc(ctx, req, headers)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}
	return r0, r1
}

// UserClient_LoginWithHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginWithHeader'
type UserClient_LoginWithHeader_Call struct {
	*mock.Call
}

// LoginWithHeader is a helper method to define mock.On call
//   - ctx context.Context
//   - req requests.LoginRequest
//   - headers map[string]string
func (_e *UserClient_Expecter) LoginWithHeader(ctx interface{}, req interface{}, headers interface{}) *UserClient_LoginWithHeader_Call {
	return &UserClient_LoginWithHeader_Call{Call: _e.mock.On("LoginWithHeader", ctx, req, headers)}
}

func (_c *UserClient_LoginWithHeader_Call) Run(run func(ctx context.Context, req requests.LoginRequest, headers map[string]string)) *UserClient_LoginWithHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 requests.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(requests.LoginRequest)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserClient_LoginWithHeader_Call) Return(tokenResponse responses.TokenResponse, edgeX errors.EdgeX) *UserClient_LoginWithHeader_Call {
	_c.Call.Return(tokenResponse, edgeX)
	return _c
}

func (_c *UserClient_LoginWithHeader_Call) RunAndReturn(run func(ctx context.Context, req requests.LoginRequest, headers map[string]string) (responses.TokenResponse, errors.EdgeX)) *UserClient_LoginWithHeader_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type UserClient
func (_mock *UserClient) Logout(ctx context.Context, headers map[string]string) errors.EdgeX {
	ret := _mock.Called(ctx, headers)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 errors.EdgeX
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) errors.EdgeX); ok {
		r0 = returnFunc(ctx, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}
	return r0
}

// UserClient_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type UserClient_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - headers map[string]string
func (_e *UserClient_Expecter) Logout(ctx interface{}, headers interface{}) *UserClient_Logout_Call {
	return &UserClient_Logout_Call{Call: _e.mock.On("Logout", ctx, headers)}
}

func (_c *UserClient_Logout_Call) Run(run func(ctx context.Context, headers map[string]string)) *UserClient_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserClient_Logout_Call) Return(edgeX errors.EdgeX) *UserClient_Logout_Call {
	_c.Call.Return(edgeX)
	return _c
}

func (_c *UserClient_Logout_Call) RunAndReturn(run func(ctx context.Context, headers map[string]string) errors.EdgeX) *UserClient_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type UserClient
func (_mock *UserClient) Update(ctx context.Context, reqs []requests.UpdateUserRequest) ([]common.BaseResponse, errors.EdgeX) {
	ret := _mock.Called(ctx, reqs)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 []common.BaseResponse
	var r1 errors.EdgeX
	if returnFunc, ok := ret.Get(0).(func(context.Context, []requests.UpdateUserRequest) ([]common.BaseResponse, errors.EdgeX)); ok {
		return returnFunc(ctx, reqs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []requests.UpdateUserRequest) []common.BaseResponse); ok {
		r0 = returnFunc(ctx, reqs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.BaseResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []requests.UpdateUserRequest) errors.EdgeX); ok {
		r1 = returnFunc(ctx, reqs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}
	return r0, r1
}

// UserClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - reqs []requests.UpdateUserRequest
func (_e *UserClient_Expecter) Update(ctx interface{}, reqs interface{}) *UserClient_Update_Call {
	return &UserClient_Update_Call{Call: _e.mock.On("Update", ctx, reqs)}
}

func (_c *UserClient_Update_Call) Run(run func(ctx context.Context, reqs []requests.UpdateUserRequest)) *UserClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []requests.UpdateUserRequest
		if args[1] != nil {
			arg1 = args[1].([]requests.UpdateUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserClient_Update_Call) Return(baseResponses []common.BaseResponse, edgeX errors.EdgeX) *UserClient_Update_Call {
	_c.Call.Return(baseResponses, edgeX)
	return _c
}

func (_c *UserClient_Update_Call) RunAndReturn(run func(ctx context.Context, reqs []requests.UpdateUserRequest) ([]common.BaseResponse, errors.EdgeX)) *UserClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UserByName provides a mock function for the type UserClient
func (_mock *UserClient) UserByName(ctx context.Context, name string) (responses.UserResponse, errors.EdgeX) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for UserByName")
	}

	var r0 responses.UserResponse
	var r1 errors.EdgeX
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (responses.UserResponse, errors.EdgeX)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) responses.UserResponse); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(responses.UserResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) errors.EdgeX); ok {
		r1 = returnFunc(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}
	return r0, r1
}

// UserClient_UserByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByName'
type UserClient_UserByName_Call struct {
	*mock.Call
}

// UserByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *UserClient_Expecter) UserByName(ctx interface{}, name interface{}) *UserClient_UserByName_Call {
	return &UserClient_UserByName_Call{Call: _e.mock.On("UserByName", ctx, name)}
}

func (_c *UserClient_UserByName_Call) Run(run func(ctx context.Context, name string)) *UserClient_UserByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserClient_UserByName_Call) Return(userResponse responses.UserResponse, edgeX errors.EdgeX) *UserClient_UserByName_Call {
	_c.Call.Return(userResponse, edgeX)
	return _c
}

func (_c *UserClient_UserByName_Call) RunAndReturn(run func(ctx context.Context, name string) (responses.UserResponse, errors.EdgeX)) *UserClient_UserByName_Call {
	_c.Call.Return(run)
	return _c
}
