// Copyright (C) 2026 IOTech Ltd
//
// Protobuf schema for EdgeX Event encoding

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pkg/protobuf/event.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event represents an EdgeX Event with one or more readings
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Unique identifier for the event (UUID)
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the device from which the event originated
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Name of the device profile from which the event originated
	ProfileName string `protobuf:"bytes,4,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	// Name of the source from which the event originated
	SourceName string `protobuf:"bytes,5,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	// Unix timestamp (nanoseconds) indicating when the event was originated at the source device
	Origin int64 `protobuf:"varint,6,opt,name=origin,proto3" json:"origin,omitempty"`
	// One or more readings captured at the time of the event
	Readings []*Reading `protobuf:"bytes,7,rep,name=readings,proto3" json:"readings,omitempty"`
	// Tags attached to the Event which give more context to the Event
	// Entire tags map is stored as JSON-encoded bytes
	Tags          []byte `protobuf:"bytes,8,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pkg_protobuf_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *Event) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *Event) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *Event) GetOrigin() int64 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *Event) GetReadings() []*Reading {
	if x != nil {
		return x.Readings
	}
	return nil
}

func (x *Event) GetTags() []byte {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Reading represents a single reading within an Event
type Reading struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the reading (UUID, optional)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unix timestamp (nanoseconds) indicating when the reading was originated at the source device
	Origin int64 `protobuf:"varint,2,opt,name=origin,proto3" json:"origin,omitempty"`
	// Name of the device from which the reading originated
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device resource name for the reading
	ResourceName string `protobuf:"bytes,4,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// Device profile name for the reading
	ProfileName string `protobuf:"bytes,5,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	// Indicates the datatype of the value property
	ValueType string `protobuf:"bytes,6,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	// Units of measurement for the reading value (optional)
	Units string `protobuf:"bytes,7,opt,name=units,proto3" json:"units,omitempty"`
	// Tags attached to the reading (optional)
	// Entire tags map is stored as JSON-encoded bytes
	Tags []byte `protobuf:"bytes,8,opt,name=tags,proto3" json:"tags,omitempty"`
	// For SimpleReading: string representation of the reading's value
	Value string `protobuf:"bytes,9,opt,name=value,proto3" json:"value,omitempty"`
	// For BinaryReading: binary value as bytes
	BinaryValue []byte `protobuf:"bytes,10,opt,name=binary_value,json=binaryValue,proto3" json:"binary_value,omitempty"`
	// For BinaryReading: media type (e.g., MIME Type)
	MediaType string `protobuf:"bytes,11,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	// For ObjectReading: object value
	// Entire object value is stored as MessagePack-encoded bytes to preserve type information
	ObjectValue []byte `protobuf:"bytes,12,opt,name=object_value,json=objectValue,proto3" json:"object_value,omitempty"`
	// For NumericReading: numeric value
	// Numeric value is stored as MessagePack-encoded bytes to preserve type information
	NumericValue []byte `protobuf:"bytes,13,opt,name=numeric_value,json=numericValue,proto3" json:"numeric_value,omitempty"`
	// Indicates if the reading value is null
	IsNull        bool `protobuf:"varint,14,opt,name=is_null,json=isNull,proto3" json:"is_null,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reading) Reset() {
	*x = Reading{}
	mi := &file_pkg_protobuf_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reading) ProtoMessage() {}

func (x *Reading) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protobuf_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reading.ProtoReflect.Descriptor instead.
func (*Reading) Descriptor() ([]byte, []int) {
	return file_pkg_protobuf_event_proto_rawDescGZIP(), []int{1}
}

func (x *Reading) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reading) GetOrigin() int64 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *Reading) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *Reading) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *Reading) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *Reading) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

func (x *Reading) GetUnits() string {
	if x != nil {
		return x.Units
	}
	return ""
}

func (x *Reading) GetTags() []byte {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Reading) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Reading) GetBinaryValue() []byte {
	if x != nil {
		return x.BinaryValue
	}
	return nil
}

func (x *Reading) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Reading) GetObjectValue() []byte {
	if x != nil {
		return x.ObjectValue
	}
	return nil
}

func (x *Reading) GetNumericValue() []byte {
	if x != nil {
		return x.NumericValue
	}
	return nil
}

func (x *Reading) GetIsNull() bool {
	if x != nil {
		return x.IsNull
	}
	return false
}

var File_pkg_protobuf_event_proto protoreflect.FileDescriptor

const file_pkg_protobuf_event_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/protobuf/event.proto\x12\bprotobuf\"\xf8\x01\n" +
	"\x05Event\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12!\n" +
	"\fprofile_name\x18\x04 \x01(\tR\vprofileName\x12\x1f\n" +
	"\vsource_name\x18\x05 \x01(\tR\n" +
	"sourceName\x12\x16\n" +
	"\x06origin\x18\x06 \x01(\x03R\x06origin\x12-\n" +
	"\breadings\x18\a \x03(\v2\x11.protobuf.ReadingR\breadings\x12\x12\n" +
	"\x04tags\x18\b \x01(\fR\x04tags\"\x9c\x03\n" +
	"\aReading\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\x03R\x06origin\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12#\n" +
	"\rresource_name\x18\x04 \x01(\tR\fresourceName\x12!\n" +
	"\fprofile_name\x18\x05 \x01(\tR\vprofileName\x12\x1d\n" +
	"\n" +
	"value_type\x18\x06 \x01(\tR\tvalueType\x12\x14\n" +
	"\x05units\x18\a \x01(\tR\x05units\x12\x12\n" +
	"\x04tags\x18\b \x01(\fR\x04tags\x12\x14\n" +
	"\x05value\x18\t \x01(\tR\x05value\x12!\n" +
	"\fbinary_value\x18\n" +
	" \x01(\fR\vbinaryValue\x12\x1d\n" +
	"\n" +
	"media_type\x18\v \x01(\tR\tmediaType\x12!\n" +
	"\fobject_value\x18\f \x01(\fR\vobjectValue\x12#\n" +
	"\rnumeric_value\x18\r \x01(\fR\fnumericValue\x12\x17\n" +
	"\ais_null\x18\x0e \x01(\bR\x06isNullB=Z;github.com/IOTechSystems/go-mod-central-ext/v4/pkg/protobufb\x06proto3"

var (
	file_pkg_protobuf_event_proto_rawDescOnce sync.Once
	file_pkg_protobuf_event_proto_rawDescData []byte
)

func file_pkg_protobuf_event_proto_rawDescGZIP() []byte {
	file_pkg_protobuf_event_proto_rawDescOnce.Do(func() {
		file_pkg_protobuf_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protobuf_event_proto_rawDesc), len(file_pkg_protobuf_event_proto_rawDesc)))
	})
	return file_pkg_protobuf_event_proto_rawDescData
}

var file_pkg_protobuf_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_protobuf_event_proto_goTypes = []any{
	(*Event)(nil),   // 0: protobuf.Event
	(*Reading)(nil), // 1: protobuf.Reading
}
var file_pkg_protobuf_event_proto_depIdxs = []int32{
	1, // 0: protobuf.Event.readings:type_name -> protobuf.Reading
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_protobuf_event_proto_init() }
func file_pkg_protobuf_event_proto_init() {
	if File_pkg_protobuf_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protobuf_event_proto_rawDesc), len(file_pkg_protobuf_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protobuf_event_proto_goTypes,
		DependencyIndexes: file_pkg_protobuf_event_proto_depIdxs,
		MessageInfos:      file_pkg_protobuf_event_proto_msgTypes,
	}.Build()
	File_pkg_protobuf_event_proto = out.File
	file_pkg_protobuf_event_proto_goTypes = nil
	file_pkg_protobuf_event_proto_depIdxs = nil
}
